Revert "pacman-rankmirrors: Update base image"
This reverts commit 50f33b029584f8b2efff2b55596ed6145cc595cf.

The following error came up during the dockerhub build:
        Starting build of index.docker.io/ecklm/pacman-rankmirrors:latest...
        Step 1/4 : FROM archlinux
        ---> 3de742be9254
        Step 2/4 : RUN pacman -Sy pacman-contrib grep --noconfirm
        ---> Running in bb82baf70473
        error: failed to initialize alpm library
        (could not find or read directory: /var/lib/pacman/)
        Removing intermediate container bb82baf70473
        The command '/bin/sh -c pacman -Sy pacman-contrib grep --noconfirm' returned a non-zero code: 255

It does not come up on local build. Will be fixed later.